// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnrZAHMEmX-BX9SMDs1uX6p4D3m1hzDpY',
    appId: '1:673027410334:web:731f95ace62f16e00e2e8f',
    messagingSenderId: '673027410334',
    projectId: 'testconfigure2-781e9',
    authDomain: 'testconfigure2-781e9.firebaseapp.com',
    storageBucket: 'testconfigure2-781e9.appspot.com',
    measurementId: 'G-ZGDVJ43NB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcNL1LgJ24tifxhBFcAlYDMmXd9I6ewjQ',
    appId: '1:673027410334:android:a666be4d63eda6d90e2e8f',
    messagingSenderId: '673027410334',
    projectId: 'testconfigure2-781e9',
    storageBucket: 'testconfigure2-781e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBMSbNKiWoBdJ-NoQ_gnT__3VXoyETMZo',
    appId: '1:673027410334:ios:8ac149bef5713b4a0e2e8f',
    messagingSenderId: '673027410334',
    projectId: 'testconfigure2-781e9',
    storageBucket: 'testconfigure2-781e9.appspot.com',
    iosBundleId: 'com.example.mobilecomputingfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBMSbNKiWoBdJ-NoQ_gnT__3VXoyETMZo',
    appId: '1:673027410334:ios:8ac149bef5713b4a0e2e8f',
    messagingSenderId: '673027410334',
    projectId: 'testconfigure2-781e9',
    storageBucket: 'testconfigure2-781e9.appspot.com',
    iosBundleId: 'com.example.mobilecomputingfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnrZAHMEmX-BX9SMDs1uX6p4D3m1hzDpY',
    appId: '1:673027410334:web:b6f543624f7df8720e2e8f',
    messagingSenderId: '673027410334',
    projectId: 'testconfigure2-781e9',
    authDomain: 'testconfigure2-781e9.firebaseapp.com',
    storageBucket: 'testconfigure2-781e9.appspot.com',
    measurementId: 'G-MD2CW16BLC',
  );
}
